# -*- coding: utf-8 -*-
"""BW_U4_N1_V2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KEU9voTuKDxFzOPfhgVfIUuQtMQ5NZDp
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors




df2 = pd.read_csv('https://raw.githubusercontent.com/kushyapp/cannabis-dataset/master/Dataset/Strains/strains-kushy_api.2017-11-14.csv')

med = df2[df2['ailment'].isnull()==False]
med = med.reset_index()
med = med[['name','type','effects','ailment','flavor']]



def strain_finder(request,outputs=10):
  """Accepts input string and integer for number of outputs
  Returns a list of tuples of strings"""
  input = [request]
  tfidf = TfidfVectorizer(stop_words='english')

  ttm = tfidf.fit_transform(med['ailment'])

  ttm = pd.DataFrame(ttm.todense(), columns=tfidf.get_feature_names())

  nn = NearestNeighbors(n_neighbors=outputs, algorithm='kd_tree')
  nn.fit(ttm)
  encoded = tfidf.transform(input)
  result =[]
  for item in nn.kneighbors(encoded.todense())[1][0]:
    info = (('name', med['name'][item]), ('type', med['type'][item]), ('effects',(med['effects'][item])),
            ('ailments', (med['ailment'][item])), ('flavors',med['flavor'][item]))
    result.append(info)
  return result



def search_name(name):
  """Name is case sensitive, most are title case.
  example **Cure for Scurvy** 
  and not **cure for scurvy**"""
  result = med[med['name']==name]
  if len(result)==0:
    return "Name not found"
  return result

search_name('A-1')

def search_type(strain):
  """ Types available are Indica, Stavia, and Hybrid"""
  strain = strain.title()
  output = med[med['type']==strain]
  if len(output)==0:
    return "Type not found"
  return output

search_type('Indica')